FROM amazonlinux:2
ENV HOME /
RUN yum update -y
RUN yum install -y rpm-build redhat-rpm-config rpmdevtools make
RUN rpmdev-setuptree
RUN echo '%dist   .amzn2' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/shogo82148.spec
RUN tar -czf /tmp/shogo82148.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
