AWSTemplateFormatVersion: 2010-09-09
Description: upload users for shogo private rpm repository

Resources:
  # https://github.com/shogo82148/fluent-bit-rpm
  FluentBitRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/fluent-bit-rpm
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/nginx-rpm
  NginxRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/nginx-rpm
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/h2o-rpm
  H2ORole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/h2o-rpm
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/redis-rpm
  RedisRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/redis-rpm
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/server-starter
  ServerStarterRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/server-starter
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/cloudwatch-logs-agent-lite
  CloudWatchLogsAgentRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/cloudwatch-logs-agent-lite
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/mitamae-rpm
  MitamaeRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/mitamae-rpm
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/go-nginx-oauth2-adapter
  OAuth2AdapterRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/go-nginx-oauth2-adapter
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/sqldef-rpm
  SqldefRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/sqldef-rpm
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/schemalex-deploy
  SchemalexDeployRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/schemalex-deploy
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/s3cli-mini
  S3cliMiniDeployRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/s3cli-mini
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/rdsmysql
  RdsMySQLDeployRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/rdsmysql
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - "sts:TagSession"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

Outputs:
  FluentBitRole:
    Value: !GetAtt FluentBitRole.Arn
  NginxRole:
    Value: !GetAtt NginxRole.Arn
  H2ORoleRole:
    Value: !GetAtt H2ORole.Arn
  RedisRole:
    Value: !GetAtt RedisRole.Arn
  ServerStarterRole:
    Value: !GetAtt ServerStarterRole.Arn
  CloudWatchLogsAgentRole:
    Value: !GetAtt CloudWatchLogsAgentRole.Arn
  MitamaeRole:
    Value: !GetAtt MitamaeRole.Arn
  OAuth2AdapterRole:
    Value: !GetAtt OAuth2AdapterRole.Arn
  SqldefRole:
    Value: !GetAtt SqldefRole.Arn
  SchemalexDeployRole:
    Value: !GetAtt SchemalexDeployRole.Arn
  S3cliMiniDeployRole:
    Value: !GetAtt S3cliMiniDeployRole.Arn
  RdsMySQLDeployRole:
    Value: !GetAtt RdsMySQLDeployRole.Arn
