AWSTemplateFormatVersion: 2010-09-09
Description: upload users for shogo private rpm repository

Resources:
  # https://github.com/shogo82148/fluent-bit-rpm
  FluentBitUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  FluentBitUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref FluentBitUser

  # https://github.com/shogo82148/nginx-rpm
  NginxUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  NginxUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref NginxUser

  # https://github.com/shogo82148/h2o-rpm
  H2OUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  H2OUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref H2OUser

Outputs:
  FluentBitUserAccessKey:
    Value: !Ref FluentBitUserAccessKey
  FluentBitUserAccessSecretKey:
    Value: !GetAtt FluentBitUserAccessKey.SecretAccessKey
  NginxUserAccessKey:
    Value: !Ref NginxUserAccessKey
  NginxUserAccessSecretKey:
    Value: !GetAtt NginxUserAccessKey.SecretAccessKey
  H2OUserAccessKey:
    Value: !Ref H2OUserAccessKey
  H2OUserAccessSecretKey:
    Value: !GetAtt H2OUserAccessKey.SecretAccessKey
