AWSTemplateFormatVersion: 2010-09-09
Description: upload users for shogo private rpm repository

Resources:
  # https://github.com/shogo82148/fluent-bit-rpm
  FluentBitUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  FluentBitUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref FluentBitUser

  # https://github.com/shogo82148/nginx-rpm
  NginxUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  NginxUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref NginxUser

  # https://github.com/shogo82148/h2o-rpm
  H2OUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  H2OUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref H2OUser

  # https://github.com/shogo82148/redis-rpm
  RedisUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  RedisUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref RedisUser

  # https://github.com/shogo82148/server-starter
  ServerStarterUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  ServerStarterUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref ServerStarterUser

  # https://github.com/shogo82148/cloudwatch-logs-agent-lite
  CloudWatchLogsAgentLiteUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  CloudWatchLogsAgentLiteUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref ServerStarterUser

  # https://github.com/shogo82148/mitamae-rpm
  MitamaeUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*
  MitamaeUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref MitamaeUser

Outputs:
  FluentBitUserAccessKey:
    Value: !Ref FluentBitUserAccessKey
  FluentBitUserAccessSecretKey:
    Value: !GetAtt FluentBitUserAccessKey.SecretAccessKey
  NginxUserAccessKey:
    Value: !Ref NginxUserAccessKey
  NginxUserAccessSecretKey:
    Value: !GetAtt NginxUserAccessKey.SecretAccessKey
  H2OUserAccessKey:
    Value: !Ref H2OUserAccessKey
  H2OUserAccessSecretKey:
    Value: !GetAtt H2OUserAccessKey.SecretAccessKey
  RedisUserAccessKey:
    Value: !Ref RedisUserAccessKey
  RedisUserAccessSecretKey:
    Value: !GetAtt RedisUserAccessKey.SecretAccessKey
  ServerStarterUserAccessKey:
    Value: !Ref ServerStarterUserAccessKey
  ServerStarterUserAccessSecretKey:
    Value: !GetAtt ServerStarterUserAccessKey.SecretAccessKey
  CloudWatchLogsAgentLiteUserAccessKey:
    Value: !Ref CloudWatchLogsAgentLiteUserAccessKey
  CloudWatchLogsAgentLiteUserAccessSecretKey:
    Value: !GetAtt CloudWatchLogsAgentLiteUserAccessKey.SecretAccessKey
  MitamaeUserAccessKey:
    Value: !Ref MitamaeUserAccessKey
  MitamaeUserAccessSecretKey:
    Value: !GetAtt MitamaeUserAccessKey.SecretAccessKey
