AWSTemplateFormatVersion: 2010-09-09
Description: upload users for shogo private rpm repository

Resources:
  # https://github.com/shogo82148/h2o-rpm
  H2ORole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/h2o-rpm:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/server-starter
  ServerStarterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/server-starter:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/cloudwatch-logs-agent-lite
  CloudWatchLogsAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/cloudwatch-logs-agent-lite:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/mitamae-rpm
  MitamaeRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148@1157344/mitamae-rpm@345042854:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/go-nginx-oauth2-adapter
  OAuth2AdapterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/go-nginx-oauth2-adapter:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/sqldef-rpm
  SqldefRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/sqldef-rpm:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/schemalex-deploy
  SchemalexDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148@1157344/schemalex-deploy@385630057:environment:release"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource:
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2027/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2027/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2027/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2023/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2023/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2023/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/10/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/10/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/10/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/9/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/9/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/9/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/8/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/8/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/8/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/10/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/10/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/10/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/9/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/9/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/9/noarch/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/8/x86_64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/8/aarch64/schemalex-deploy/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/8/noarch/schemalex-deploy/*
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary
                Condition:
                  StringLike:
                    "s3:prefix":
                      - amazonlinux/2027/x86_64/schemalex-deploy/*
                      - amazonlinux/2027/aarch64/schemalex-deploy/*
                      - amazonlinux/2027/noarch/schemalex-deploy/*
                      - amazonlinux/2023/x86_64/schemalex-deploy/*
                      - amazonlinux/2023/aarch64/schemalex-deploy/*
                      - amazonlinux/2023/noarch/schemalex-deploy/*
                      - almalinux/10/x86_64/schemalex-deploy/*
                      - almalinux/10/aarch64/schemalex-deploy/*
                      - almalinux/10/noarch/schemalex-deploy/*
                      - almalinux/9/x86_64/schemalex-deploy/*
                      - almalinux/9/aarch64/schemalex-deploy/*
                      - almalinux/9/noarch/schemalex-deploy/*
                      - almalinux/8/x86_64/schemalex-deploy/*
                      - almalinux/8/aarch64/schemalex-deploy/*
                      - almalinux/8/noarch/schemalex-deploy/*
                      - rockylinux/10/x86_64/schemalex-deploy/*
                      - rockylinux/10/aarch64/schemalex-deploy/*
                      - rockylinux/10/noarch/schemalex-deploy/*
                      - rockylinux/9/x86_64/schemalex-deploy/*
                      - rockylinux/9/aarch64/schemalex-deploy/*
                      - rockylinux/9/noarch/schemalex-deploy/*
                      - rockylinux/8/x86_64/schemalex-deploy/*
                      - rockylinux/8/aarch64/schemalex-deploy/*
                      - rockylinux/8/noarch/schemalex-deploy/*

  # https://github.com/shogo82148/s3cli-mini
  S3cliMiniDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/s3cli-mini:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/rdsmysql
  RdsMySQLDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148@1157344/rdsmysql@128398244:environment:release"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource:
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2027/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2027/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2027/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2023/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2023/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/amazonlinux/2023/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/10/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/10/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/10/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/9/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/9/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/9/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/8/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/8/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/almalinux/8/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/10/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/10/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/10/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/9/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/9/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/9/noarch/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/8/x86_64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/8/aarch64/rdsmysql/*
                  - arn:aws:s3:::shogo82148-rpm-temporary/rockylinux/8/noarch/rdsmysql/*
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary
                Condition:
                  StringLike:
                    "s3:prefix":
                      - amazonlinux/2027/x86_64/rdsmysql/*
                      - amazonlinux/2027/aarch64/rdsmysql/*
                      - amazonlinux/2027/noarch/rdsmysql/*
                      - amazonlinux/2023/x86_64/rdsmysql/*
                      - amazonlinux/2023/aarch64/rdsmysql/*
                      - amazonlinux/2023/noarch/rdsmysql/*
                      - almalinux/10/x86_64/rdsmysql/*
                      - almalinux/10/aarch64/rdsmysql/*
                      - almalinux/10/noarch/rdsmysql/*
                      - almalinux/9/x86_64/rdsmysql/*
                      - almalinux/9/aarch64/rdsmysql/*
                      - almalinux/9/noarch/rdsmysql/*
                      - almalinux/8/x86_64/rdsmysql/*
                      - almalinux/8/aarch64/rdsmysql/*
                      - almalinux/8/noarch/rdsmysql/*
                      - rockylinux/10/x86_64/rdsmysql/*
                      - rockylinux/10/aarch64/rdsmysql/*
                      - rockylinux/10/noarch/rdsmysql/*
                      - rockylinux/9/x86_64/rdsmysql/*
                      - rockylinux/9/aarch64/rdsmysql/*
                      - rockylinux/9/noarch/rdsmysql/*
                      - rockylinux/8/x86_64/rdsmysql/*
                      - rockylinux/8/aarch64/rdsmysql/*
                      - rockylinux/8/noarch/rdsmysql/*

  # https://github.com/shogo82148/sets3lock
  SetS3LockDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148/sets3lock:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

  # https://github.com/shogo82148/mysql-rpm
  MySQLRpmDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/tok\
                en.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:shogo82148@1157344/mysql-rpm@1376915789:*"
      Policies:
        - PolicyName: upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: arn:aws:s3:::shogo82148-rpm-temporary/*

Outputs:
  H2ORoleRole:
    Value: !GetAtt H2ORole.Arn
  ServerStarterRole:
    Value: !GetAtt ServerStarterRole.Arn
  CloudWatchLogsAgentRole:
    Value: !GetAtt CloudWatchLogsAgentRole.Arn
  MitamaeRole:
    Value: !GetAtt MitamaeRole.Arn
  OAuth2AdapterRole:
    Value: !GetAtt OAuth2AdapterRole.Arn
  SqldefRole:
    Value: !GetAtt SqldefRole.Arn
  SchemalexDeployRole:
    Value: !GetAtt SchemalexDeployRole.Arn
  S3cliMiniDeployRole:
    Value: !GetAtt S3cliMiniDeployRole.Arn
  RdsMySQLDeployRole:
    Value: !GetAtt RdsMySQLDeployRole.Arn
  SetS3LockDeployRole:
    Value: !GetAtt SetS3LockDeployRole.Arn
  MySQLRpmDeployRole:
    Value: !GetAtt MySQLRpmDeployRole.Arn
