FROM almalinux/almalinux:8
ENV HOME /
RUN dnf update -y
RUN dnf install -y rpm-build redhat-rpm-config rpmdevtools make
RUN rpmdev-setuptree
RUN echo '%dist   .el8' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/mackerel.spec
RUN tar -czf /tmp/mackerel.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
