FROM centos:7
ENV HOME /
RUN yum update -y
RUN yum install -y rpm-build redhat-rpm-config rpmdevtools make
RUN rpmdev-setuptree
RUN echo '%dist   .el7' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/mackerel.spec
RUN tar -czf /tmp/mackerel.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
