AWSTemplateFormatVersion: 2010-09-09
Description: shogo private rpm repository
Transform: AWS::Serverless-2016-10-31

Parameters:
  RPMBucketName:
    Type: String
    Description: S3 bucket name for RPM repository
  RPMTemporaryBucketName:
    Type: String
    Description: S3 bucket name for uploading RPM temporary
  GPGSecret:
    Type: AWS::SSM::Parameter::Name
    Description: SSM Parameter name for GPG Secret key

Resources:
  RPMBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref RPMBucketName
      AccessControl: PublicRead

  RPMTemporaryBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref RPMTemporaryBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  Locker:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  MetadataUpdater:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
      MemorySize: 512
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref RPMTemporaryBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            # we can't write "!Ref RPMTemporaryBucket" because of Circular dependency between resources
            BucketName: !Ref RPMTemporaryBucketName
        - S3CrudPolicy:
            BucketName: !Ref RPMBucket
        - SSMParameterReadPolicy:
            # HACK: trim "/" prefix
            ParameterName: !Join ["", !Split ["^/", !Sub "^${GPGSecret}"]]
        - DynamoDBCrudPolicy:
            TableName: !Ref Locker
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref RPMBucket
          GPG_SECRET_KEY: !Ref GPGSecret
          LOCKER_TABLE: !Ref Locker
    Metadata:
      DockerTag: latest
      DockerContext: ./metadata-updater
      Dockerfile: Dockerfile
