AWSTemplateFormatVersion: 2010-09-09
Description: shogo private rpm repository
Transform: AWS::Serverless-2016-10-31

Resources:
  RPMBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: shogo82148-rpm-repository
      AccessControl: PublicRead

  RPMTemporaryBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: shogo82148-rpm-temporary
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MetadataUpdater:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
      MemorySize: 3008
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref RPMTemporaryBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            # we can't write "!Ref RPMTemporaryBucket" because of Circular dependency between resources
            BucketName: shogo82148-rpm-temporary
        - S3CrudPolicy:
            BucketName: !Ref RPMBucket
        - SSMParameterReadPolicy:
            ParameterName: "shogo82148/gpg/secret"
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref RPMBucket
          GPG_SECRET_KEY: "shogo82148/gpg/secret"
    Metadata:
      DockerTag: latest
      DockerContext: ./metadata-updater
      Dockerfile: Dockerfile
