FROM amazonlinux:2022.0.20221207.4
ENV HOME /
RUN dnf update -y
RUN dnf install -y rpm-build redhat-rpm-config rpmdevtools make
RUN rpmdev-setuptree
RUN echo '%dist   .amzn2022' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/shogo82148.spec
RUN tar -czf /tmp/shogo82148.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
