name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lambda:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: build
        run: |
          make build
        working-directory: "lambda"

  mackerel:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: build
        run: |
          make all
        working-directory: "yum.repos/mackerel"

  shogo82148:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: build
        run: |
          make all
        working-directory: "yum.repos/shogo82148"
