name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lambda:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: build
        run: |
          make build
        working-directory: "lambda"

  mackerel:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: build
        run: |
          make all
        working-directory: "yum.repos/mackerel"

  shogo82148:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: build
        run: |
          make all
        working-directory: "yum.repos/shogo82148"
